FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /code

RUN get-app update && apt-get install -y --no-install-recommends \ 
    curl \ && rm -rf /var/lib/apt/lists*

COPY requirements.txt .
RUN pip install --no-cashe-dir -r requirements.txt
COPY  app ./app
COPY  worker ./worker
COPY  clembic ./clembic
COPY clembic.ini ./clembic.ini

EXPOSE 8000