"""create import_jobs

Revision ID: a28e3f62a98c
Revises: 
Create Date: 2026-01-20 01:24:38.374339

"""
from alembic import op
import sqlalchemy as sa

revision = 'a28e3f62a98c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_jobs')
    # ### end Alembic commands ###